export const APP_NAME = "MyBusinessesLeads";
export const APP_SHORT = "MBL";
export const APP_TAGLINE = "Find, qualify, and reach local businesses — faster.";

/** Max rows per manual enrichment action (guess / social / email scrape). */
export const MAX_ENRICHMENT_SELECTION = 20;

export const BUSINESS_TYPES: Record<string, string> = {
  all: "All Business Types",
  hair_salon: "Hair Salon",
  beauty_salon: "Beauty Salon",
  nail_salon: "Nail Salon",
  spa: "Spa",
  bakery: "Bakery",
  restaurant: "Restaurant",
  cafe: "Cafe / Coffee Shop",
  bar: "Bar",
  gym: "Gym / Fitness",
  dentist: "Dentist",
  doctor: "Doctor / GP",
  hospital: "Hospital",
  veterinary_care: "Veterinarian",
  pharmacy: "Pharmacy",
  car_repair: "Auto Repair",
  florist: "Florist",
  pet_store: "Pet Store",
  clothing_store: "Clothing Store",
  electronics_store: "Electronics Store",
  supermarket: "Supermarket",
  furniture_store: "Furniture Store",
  hardware_store: "Hardware Store",
  laundry: "Laundry",
  real_estate_agency: "Real Estate Agency",
  travel_agency: "Travel Agency",
  accounting: "Accounting",
  lawyer: "Lawyer",
  insurance_agency: "Insurance Agency",
  hotel: "Hotel",
  school: "School",
};

export const OSM_TAGS: Record<string, [string, string][]> = {
  hair_salon: [
    ["shop", "hairdresser"],
    ["shop", "hair"],
    ["amenity", "hairdresser"],
  ],
  beauty_salon: [
    ["shop", "beauty"],
    ["shop", "cosmetics"],
    ["shop", "makeup"],
    ["amenity", "beauty_salon"],
  ],
  nail_salon: [
    ["shop", "nail_salon"],
    ["shop", "nails"],
  ],
  spa: [
    ["leisure", "spa"],
    ["amenity", "spa"],
    ["amenity", "massage"],
    ["leisure", "sauna"],
  ],
  bakery: [
    ["shop", "bakery"],
    ["craft", "bakery"],
    ["shop", "pastry"],
    ["shop", "confectionery"],
    ["shop", "bread"],
  ],
  restaurant: [
    ["amenity", "restaurant"],
    ["amenity", "fast_food"],
    ["amenity", "food_court"],
  ],
  cafe: [
    ["amenity", "cafe"],
    ["amenity", "coffee_shop"],
    ["shop", "coffee"],
    ["shop", "tea"],
  ],
  bar: [
    ["amenity", "bar"],
    ["amenity", "pub"],
    ["amenity", "nightclub"],
    ["amenity", "biergarten"],
  ],
  gym: [
    ["leisure", "fitness_centre"],
    ["amenity", "gym"],
    ["leisure", "sports_centre"],
    ["leisure", "sports_hall"],
    ["leisure", "swimming_pool"],
  ],
  dentist: [
    ["amenity", "dentist"],
    ["healthcare", "dentist"],
    ["healthcare:speciality", "dentistry"],
  ],
  doctor: [
    ["amenity", "doctors"],
    ["healthcare", "doctor"],
    ["amenity", "clinic"],
    ["healthcare", "clinic"],
    ["amenity", "health_centre"],
  ],
  hospital: [
    ["amenity", "hospital"],
    ["healthcare", "hospital"],
  ],
  veterinary_care: [
    ["amenity", "veterinary"],
    ["healthcare", "veterinary"],
    ["shop", "veterinary"],
  ],
  pharmacy: [
    ["amenity", "pharmacy"],
    ["healthcare", "pharmacy"],
    ["shop", "chemist"],
    ["shop", "drugstore"],
  ],
  car_repair: [
    ["shop", "car_repair"],
    ["amenity", "car_repair"],
    ["shop", "car_parts"],
    ["craft", "car_repair"],
    ["shop", "mechanic"],
    ["craft", "mechanic"],
    ["amenity", "vehicle_inspection"],
  ],
  florist: [
    ["shop", "florist"],
    ["shop", "flowers"],
  ],
  pet_store: [
    ["shop", "pet"],
    ["shop", "aquarium"],
    ["shop", "pet_grooming"],
    ["amenity", "pet_store"],
  ],
  clothing_store: [
    ["shop", "clothes"],
    ["shop", "fashion"],
    ["shop", "boutique"],
    ["shop", "second_hand"],
    ["shop", "shoes"],
    ["shop", "accessories"],
  ],
  electronics_store: [
    ["shop", "electronics"],
    ["shop", "computer"],
    ["shop", "mobile_phone"],
    ["shop", "appliance"],
    ["shop", "hifi"],
    ["shop", "radiotechnics"],
  ],
  supermarket: [
    ["shop", "supermarket"],
    ["shop", "grocery"],
    ["shop", "convenience"],
    ["shop", "general"],
    ["shop", "wholesale"],
  ],
  furniture_store: [
    ["shop", "furniture"],
    ["shop", "interior_decoration"],
    ["shop", "houseware"],
    ["shop", "antiques"],
    ["shop", "bed"],
  ],
  hardware_store: [
    ["shop", "hardware"],
    ["shop", "doityourself"],
    ["shop", "tools"],
    ["shop", "building_materials"],
    ["shop", "paint"],
  ],
  laundry: [
    ["shop", "laundry"],
    ["amenity", "laundry"],
    ["shop", "dry_cleaning"],
    ["amenity", "dry_cleaning"],
  ],
  real_estate_agency: [
    ["office", "real_estate"],
    ["office", "estate_agent"],
    ["amenity", "real_estate_agency"],
  ],
  travel_agency: [
    ["shop", "travel_agency"],
    ["office", "travel_agent"],
    ["amenity", "travel_agency"],
  ],
  accounting: [
    ["office", "accountant"],
    ["office", "tax_advisor"],
    ["office", "financial"],
    ["office", "financial_advisor"],
  ],
  lawyer: [
    ["office", "lawyer"],
    ["office", "legal"],
    ["office", "notary"],
    ["office", "attorney"],
  ],
  insurance_agency: [
    ["office", "insurance"],
    ["office", "insurance_agency"],
  ],
  hotel: [
    ["tourism", "hotel"],
    ["tourism", "motel"],
    ["tourism", "guest_house"],
    ["tourism", "hostel"],
    ["amenity", "hotel"],
  ],
  school: [
    ["amenity", "school"],
    ["amenity", "college"],
    ["amenity", "university"],
    ["amenity", "kindergarten"],
    ["amenity", "language_school"],
    ["amenity", "driving_school"],
  ],
};

export const FETCH_HEADERS = {
  "User-Agent": "MyBusinessesLeads/1.0 (lead research tool)",
  "Accept-Language": "en-US,en;q=0.9",
};
